#!/usr/bin/env bash
set -euo pipefail

fail () {
  echo $1
  exit 1
}

check_webdriver () {
  local selenium=${SELENIUM_URL:-'http://localhost:4444/wd/hub'}
  curl -s -i ${selenium}/status | grep success > /dev/null
}

retry_check () {
  local retries=${1}
  local func=${2}
  local interval=3
  for i in $(seq 1 ${retries})
  do
    ("${func}") \
      || (echo -n "." && sleep ${interval} && "${func}") \
      && break
  done
}

check_webdriver_retrier () {
  echo -n 'Checking Selenium Webdriver...'
  retry_check 5 check_webdriver || fail "Selenium Webdriver is not running, use 'make selenium' or 'make integration.dev'"
}

check_webdriver_retrier

echo 'Starting Protractor...'
protractor integration/protractor.config.js
